config/routes.rb
WolfT::Application.routes.draw do
  root to: 'statics#landing'

  resources :tshirts, only: :index
  get '/show_stock', to: 'tshirts#show_stock'

  get '/feature', to: 'statics#feature'
  get '/about', to: 'statics#about'
  get '/basket', to: 'statics#basket'

  post '/add', to: 'baskets#add'
  get '/empty', to: 'baskets#empty'

  post '/checkoutform', to: 'orders#checkoutform'

end

app/models/inventory.rb
class Inventory
  include Mongoid::Document

  field :qty, type: Integer, default: 1

  belongs_to :tshirt
  belongs_to :tsize

end

app/models/order.rb
class Order
  include Mongoid::Document

  field :stripeToken
  field :stripeEmail
  field :stripeBillingName
  field :stripeBillingAddressLine1
  field :stripeBillingAddressZip
  field :stripeBillingAddressCity
  field :stripeBillingAddressState
  field :stripeBillingAddressCountry

  field :stripeShippingName
  field :stripeShippingAddressLine1
  field :stripeShippingAddressZip
  field :stripeShippingAddressCity
  field :stripeShippingAddressState
  field :stripeShippingAddressCountry

  field :basketTotal
  field :basketItemQuantity
  field :basketDescription

  field :record_number

  validates_uniqueness_of :record_number
  validates_presence_of :record_number

  def create_record_number
    self.update_attributes(record_number: generate_record_number)
  end

  def generate_record_number(size = 6)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    record_no = (0...size).map { charset.to_a[rand(charset.size)] }.join
  end
end

app/models/picture.rb
class Picture
  include Mongoid::Document

  field :image_name, default: 'placeholder.png'
  field :view

  validates_presence_of :view, :image_name
  validates_uniqueness_of :image_name

  belongs_to :tshirt
end

app/models/size.rb
class Size
  include Mongoid::Document

  field :name, type: String

  belongs_to :tshirt

  validates_presence_of :name
end

app/models/tshirt.rb
class Tshirt
  include Mongoid::Document

  field :name
  field :description
  field :cost, type: Integer

  has_many :inventory
  has_many :picture

  validates_presence_of :name, :description, :cost
  validates_uniqueness_of :name

  def sizes
    inventory.map(&:tsize).map { |size| size.name.upcase }
  end

  def front
    picture.where(view: "front").pluck(:image_name).first
  end

  def back
    picture.where(view: "back").pluck(:image_name).first
  end

  def self.stock(tshirt, tsize)
    Inventory.where(tshirt: tshirt, tsize: tsize).pluck(:qty).first
  end

end

app/models/tsize.rb
class Tsize
  include Mongoid::Document

  field :name, type: String

  has_many :inventory

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  include BasketUsage

  def add
    data = { id: "#{params[:tshirt][:name]} - #{params[:tshirt][:size]}",
             type: params[:tshirt].class,
             unit_cost: params[:tshirt][:cost],
             quantity: params[:tshirt][:qty] }
    basket.add_item(data)
    render "statics/basket", layout: false
  end

  def empty
    clear_basket
    render "statics/basket", layout: false
  end
end

app/controllers/concerns/order_processor.rb
module OrderProcessor
  extend ActiveSupport::Concern
  include BasketUsage

  def make_stripe_charge
    begin
      new_basket
      charge = Stripe::Charge.create(
        :card  => params[:stripeToken],
        :amount      => basket_in_cents,
        :description => 'Hungry Wolft Tshirts',
        :currency    => 'usd'
      )
    rescue Stripe::CardError => e
      flash[:error] = e.message
    end
  end

  def log_order
    order = Order.new(order_params)
    order.basketTotal = basket_in_cents
    order.basketItemQuantity = basket.quantity
    order.basketDescription = "basket description"
    order.create_record_number
    order
  end

  def generate_notice(order)
    clear_basket

    OrderMailer.confirmation_email(
                  email: @order.stripeEmail,
                  record_number: @order.record_number,
                  name: order.stripeBillingName,
                  order_total: order.basketTotal,
                  order_description: order.basketDescription,
                  order_qty: order.basketItemQuantity
                ).deliver

    flash[:notice] = "Your order confirmation number is #{@order.record_number}"
    flash.keep(:notice)
  end

end

app/controllers/concerns/sslredirect.rb
module Sslredirect
  extend ActiveSupport::Concern

  def enforce_ssl
    redirect_to :protocol => "https://" if unsecure
  end

  private

  def unsecure
    (request.protocol == "http://") && production?
  end

  def production?
    Rails.env.production?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrderProcessor

  def checkoutform
    make_stripe_charge
    @order = log_order

    if @order.save
      generate_notice(@order)
      redirect_to root_path
    else
      render "statics/basket"
    end
  end

  private

  def order_params
    params.permit(:stripeToken,
                  :stripeEmail,
                  :stripeBillingName,
                  :stripeBillingAddressLine1,
                  :stripeBillingAddressZip,
                  :stripeBillingAddressCity,
                  :stripeBillingAddressState,
                  :stripeBillingAddressCountry,
                  :stripeShippingName,
                  :stripeShippingAddressLine1,
                  :stripeShippingAddressZip,
                  :stripeShippingAddressCity,
                  :stripeShippingAddressState,
                  :stripeShippingAddressCountry)
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  include BasketUsage
  include Sslredirect

  def landing
    enforce_ssl
    new_basket
    @tshirts = Tshirt.all
  end

  def feature
    @tshirts = Tshirt.all
    render 'statics/landing', layout: false
  end

  def about
    render 'statics/about', layout: false
  end

  def basket
    render 'statics/basket', layout: false
  end

end

app/controllers/tshirts_controller.rb
class TshirtsController < ApplicationController
  include BasketUsage

  def index
    @tshirts = Tshirt.all
    render "tshirts/index", layout: false
  end

  def show_stock
    tshirt = Tshirt.where(name: params[:tshirt][:name]).first
    tsize = Tsize.where(name: params[:tshirt][:size].downcase).first
    @inventory_qty = Tshirt.stock tshirt, tsize
    render json: [*1..@inventory_qty]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include BasketUsage
end

app/views/banners/_aboutpage_images.html.haml
%div#about-images
  = image_tag "folks.jpg"

app/views/banners/_frontpage_images.html.haml
%div#band-images
  = image_tag 'banner_splash.jpg'

%div.box
  %p
    duran duran

app/views/banners/_inventorypage_images.html.haml
%div#band-images
  = image_tag 'banner_index.jpg'

%div.box
  %p
    the fab five

app/views/layouts/_brand.html.haml
.brand_heading
  .brand= link_to "Hungry Wolf T Shirts", feature_path, remote: true, id: "feature"

%div.lines
  .line
  .line
  .line

app/views/layouts/_footer.html.haml
.copyright
  © 2013 HungryWolfTShirts Inc.
.author
  Built by
  %a{href: "http://chaeokeefe.com"} Chae O'Keefe

app/views/layouts/_navbar.html.haml
%ul
  %li= link_to "Inventory", tshirts_path, remote: true, id: "inventory", class: "show-for-medium-up"
  %li= link_to "About", about_path, remote: true, id: "about"
  %li= link_to "Basket", basket_path, remote: true, id: "basket"

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{lang: "en"}
  / <![endif]
  %head
    %meta{charset: "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "HungryWolfTShirts"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags

  %body
    %header
      = render "/layouts/brand"
      %nav= render "/layouts/navbar"
    %section#maincontent
      = yield
    %footer
      = render "/layouts/footer"
    %div.Modal.reveal-modal#myModal
      Modal!
    %div.Modal.reveal-modal#myModalConfirmation
      Confirmation!
    = javascript_include_tag "application"

app/views/orders/_checkout.html.haml
= flash[:error]

Your order has been placed!
%br
Confirmation Number:
= @order.record_number

app/views/statics/_checkout.html.haml
= form_tag checkoutform_path, id: 'stripe_checkout_form' do
  %article
    %label.amount
      %span Amount: #{basket_amount}
  %script.stripe-button{"data-amount" => "#{basket_in_cents}", "data-name" => "Hungry Wolf T-Shirts", "data-description" => "Test: 4242 4242 4242 4242", "data-billing-address" => true, "data-shipping-address" => true, "data-key" => Rails.configuration.stripe[:publishable_key], src: "https://checkout.stripe.com/checkout.js"}

app/views/statics/_frontpage.html.haml
%div#feature-tshirt.show-for-medium-up
  = render 'banners/frontpage_images'

  %ul.example-orbit{"data-orbit" => "", "data-options" => "timer_speed:2500"}
    - @tshirts.each do |tshirt|
      %li.tshirt_feature
        .tshirt_images
          .front
            = image_tag tshirt.front || 'placeholder.png'
          .back
            = image_tag tshirt.back || 'placeholder.png'
        .tshirt_info
          .circleBase
            .text
              %b= tshirt.name
              %p= tshirt.description
              %p
                sizes: #{tshirt.sizes.join(", ")}
              %p
                cost: #{number_to_currency tshirt.cost}

%div.show-for-small
  = render 'tshirts/allshirts'

app/views/statics/about.html.haml
.row.about
  .small-12.columns.small-centered.feature
    %p
      %b INSPIRATION
      In dedication to the prettiest boys in rock,
      \#{link_to "Duran Duran", "http://www.duranduran.com/"}
      t-shirts live on from the early 80's. You remember the hits:

      \#{link_to "Ordinary World", "http://www.youtube.com/watch?v=dDLiVwpv89s"},
      \#{link_to "Girls on Film", "http://vimeo.com/18521738"},
      \#{link_to "Hungry Like the Wolf", "http://www.youtube.com/watch?v=oOg5VxrRTi0"},
      \#{link_to "Rio", "http://www.youtube.com/watch?v=e3W6yf6c-FA&feature=kp"},
      \#{link_to "Come Undone", "http://www.youtube.com/watch?v=ICnlyNUt_0o"}...
    %p
      %b THE GOODS
      All t-shirts were fabricated in the 80's, and have been neatly stocked away for 20 years. None of the shirts have been worn, and are in mint condition.
    %p
      %b WHERE DID THEY COME FROM?
      When my in-laws were studying at Cornell in the 70's, they would sell rock t-shirts outside of music venues on the weekends. After graduation, they started a mail-order t-shirt company called 'On Top', one of the first of its kind. Sadly, they didn't transition into e-commerce. But luckily for you, they have an impressive inventory of merchandise left over.

= render 'banners/aboutpage_images'

app/views/statics/basket.html.haml
= flash[:errors]
- if basket.items.empty?
  Basket is empty!
- else
  %ul
    - basket.items.each do |item|
      %li #{item.quantity} #{item.id} @ #{item.unit_cost}

  = render partial: 'statics/checkout'
  %button.btn#ClearBasket= 'empty basket'

app/views/statics/landing.html.haml
- if flash[:notice]
  %div#flashNotice{:style=>"display:none"}
    %p Thank you!
    = flash[:notice]

%div
  = render partial: "frontpage"

app/views/tshirts/_allshirts.html.haml
= render partial: '/banners/inventorypage_images'

%div.row
  %div.large-centered.columns.large-10.show-for-medium-up
    = render partial: "tshirts/large"

  %div.hide-for-medium-up
    = render partial: "tshirts/small"

app/views/tshirts/_form.html.haml
%div.tshirt_form
  = form_tag('/add', method: :post, id: 'tform') do |f|
    %div.selectors
      %div.sizes
        Sizes:
      %div.qty
        Quantity:
      %div.form_fields
        %div.sizes
          .tselect= select(:tshirt, "size", tshirt.sizes, { include_blank: true })
        %div.qty
          .tselect= select(:tshirt, "qty", '')
    %div.basketbutton
      = button_tag 'Add to Basket', class: 'AddToBasket button tiny'

    = hidden_field :tshirt, :name, :value => tshirt.name
    = hidden_field :tshirt, :cost, :value => tshirt.cost

app/views/tshirts/_large.html.haml
%ul.allTs
  - @tshirts.each do |t|
    %li
      .row.tshirt
        .container.columns.large-4
          .container
            = image_tag((t.front || "placeholder.png"), class: "index-image")

        .container.column.large-8
          .about.info
            %b= t.name
            %br= t.description
            \ $#{t.cost}
            = render partial: "tshirts/form", locals: { tshirt: t }

app/views/tshirts/_small.html.haml
%ul.allTs-small
  - @tshirts.each do |t|
    %li
      .row.tshirt
        .container.columns.large-4
          .container
            = image_tag((t.front || "placeholder.png"), class: "index-image")

        .container.column.large-8.info
          %b= t.name
          %br= t.description
          \ $#{t.cost}
          = render partial: "tshirts/form", locals: { tshirt: t }

app/views/tshirts/index.html.haml
= render partial: 'allshirts'